resources:
  - ../../base

configMapGenerator:
  - name: pass-api-config
    behavior: merge
    literals:
      - DD_ENV=dev
      - DD_VERSION=6b3aafab7e4a947c0aa359213909b12ed6e80b29

  - name: pass-summary-api-config
    behavior: merge
    literals:
      - DD_ENV=dev
      - DD_VERSION=6b3aafab7e4a947c0aa359213909b12ed6e80b29

  - name: pass-image-api-config
    behavior: merge
    literals:
      - DD_ENV=dev
      - DD_VERSION=6b3aafab7e4a947c0aa359213909b12ed6e80b29

  - name: load-test-service-config
    behavior: merge
    literals:
      - DD_ENV=dev
      - DD_VERSION=6b3aafab7e4a947c0aa359213909b12ed6e80b29

images:
  - name: ghcr.io/scottgerring/sdlc-gitops-sample-stack/pass-api
    newTag: "6b3aafab7e4a947c0aa359213909b12ed6e80b29"

  - name: ghcr.io/scottgerring/sdlc-gitops-sample-stack/pass-summary-api
    newTag: "6b3aafab7e4a947c0aa359213909b12ed6e80b29"

  - name: ghcr.io/scottgerring/sdlc-gitops-sample-stack/pass-image-api
    newTag: "6b3aafab7e4a947c0aa359213909b12ed6e80b29"

  - name: ghcr.io/scottgerring/sdlc-gitops-sample-stack/load-test-service
    newTag: "6b3aafab7e4a947c0aa359213909b12ed6e80b29"
