resources:
  - ../../base

configMapGenerator:
  - name: pass-api-config
    behavior: merge
    literals:
      - DD_ENV=dev
      - DD_VERSION=a5b48056d5b3e00681b4811263a5f7a0393a2da0

  - name: pass-summary-api-config
    behavior: merge
    literals:
      - DD_ENV=dev
      - DD_VERSION=a5b48056d5b3e00681b4811263a5f7a0393a2da0

  - name: pass-image-api-config
    behavior: merge
    literals:
      - DD_ENV=dev
      - DD_VERSION=a5b48056d5b3e00681b4811263a5f7a0393a2da0

  - name: load-test-service-config
    behavior: merge
    literals:
      - DD_ENV=dev
      - DD_VERSION=a5b48056d5b3e00681b4811263a5f7a0393a2da0

images:
  - name: ghcr.io/scottgerring/sdlc-gitops-sample-stack/pass-api
    newTag: "a5b48056d5b3e00681b4811263a5f7a0393a2da0"

  - name: ghcr.io/scottgerring/sdlc-gitops-sample-stack/pass-summary-api
    newTag: "a5b48056d5b3e00681b4811263a5f7a0393a2da0"

  - name: ghcr.io/scottgerring/sdlc-gitops-sample-stack/pass-image-api
    newTag: "a5b48056d5b3e00681b4811263a5f7a0393a2da0"

  - name: ghcr.io/scottgerring/sdlc-gitops-sample-stack/load-test-service
    newTag: "a5b48056d5b3e00681b4811263a5f7a0393a2da0"
