resources:
  - ../../base

configMapGenerator:
  - name: pass-api-config
    behavior: merge
    literals:
      - DD_ENV=dev
      - DD_VERSION=cfebc77765827d0acbe07b2ec7b8946fa41afabb

  - name: pass-summary-api-config
    behavior: merge
    literals:
      - DD_ENV=dev
      - DD_VERSION=cfebc77765827d0acbe07b2ec7b8946fa41afabb

  - name: pass-image-api-config
    behavior: merge
    literals:
      - DD_ENV=dev
      - DD_VERSION=cfebc77765827d0acbe07b2ec7b8946fa41afabb

  - name: load-test-service-config
    behavior: merge
    literals:
      - DD_ENV=dev
      - DD_VERSION=cfebc77765827d0acbe07b2ec7b8946fa41afabb

images:
  - name: ghcr.io/datadog/sdlc-gitops-sample-stack/pass-api
    newTag: "cfebc77765827d0acbe07b2ec7b8946fa41afabb"

  - name: ghcr.io/datadog/sdlc-gitops-sample-stack/pass-summary-api
    newTag: "cfebc77765827d0acbe07b2ec7b8946fa41afabb"

  - name: ghcr.io/datadog/sdlc-gitops-sample-stack/pass-image-api
    newTag: "cfebc77765827d0acbe07b2ec7b8946fa41afabb"

  - name: ghcr.io/datadog/sdlc-gitops-sample-stack/load-test-service
    newTag: "cfebc77765827d0acbe07b2ec7b8946fa41afabb"
