resources:
  - ../../base

configMapGenerator:
  - name: pass-api-config
    behavior: merge
    literals:
      - DD_ENV=dev
      - DD_VERSION=4614d75d9bb34ea3bcdcf40204ec611927b0ba0f

  - name: pass-summary-api-config
    behavior: merge
    literals:
      - DD_ENV=dev
      - DD_VERSION=4614d75d9bb34ea3bcdcf40204ec611927b0ba0f

  - name: pass-image-api-config
    behavior: merge
    literals:
      - DD_ENV=dev
      - DD_VERSION=4614d75d9bb34ea3bcdcf40204ec611927b0ba0f

images:
  - name: ghcr.io/scottgerring/sdlc-gitops-sample-stack/pass-api
    newTag: "4614d75d9bb34ea3bcdcf40204ec611927b0ba0f"

  - name: ghcr.io/scottgerring/sdlc-gitops-sample-stack/pass-summary-api
    newTag: "4614d75d9bb34ea3bcdcf40204ec611927b0ba0f"

  - name: ghcr.io/scottgerring/sdlc-gitops-sample-stack/pass-image-api
    newTag: "4614d75d9bb34ea3bcdcf40204ec611927b0ba0f"
