resources:
  - ../../base

# Patches for resources
patchesStrategicMerge:
  - aws-ingress-patch.yaml

configMapGenerator:
  - name: pass-api-config
    behavior: merge
    literals:
      - DD_ENV=dev
      - DD_VERSION=2113e1c327c0a334e2488d6210585614dc8e6be8

  - name: pass-summary-api-config
    behavior: merge
    literals:
      - DD_ENV=dev
      - DD_VERSION=2113e1c327c0a334e2488d6210585614dc8e6be8

  - name: pass-image-api-config
    behavior: merge
    literals:
      - DD_ENV=dev
      - DD_VERSION=2113e1c327c0a334e2488d6210585614dc8e6be8

  - name: load-test-service-config
    behavior: merge
    literals:
      - DD_ENV=dev
      - DD_VERSION=2113e1c327c0a334e2488d6210585614dc8e6be8

images:
  - name: ghcr.io/scottgerring/sdlc-gitops-sample-stack/pass-api
    newTag: "2113e1c327c0a334e2488d6210585614dc8e6be8"

  - name: ghcr.io/scottgerring/sdlc-gitops-sample-stack/pass-summary-api
    newTag: "2113e1c327c0a334e2488d6210585614dc8e6be8"

  - name: ghcr.io/scottgerring/sdlc-gitops-sample-stack/pass-image-api
    newTag: "2113e1c327c0a334e2488d6210585614dc8e6be8"

  - name: ghcr.io/scottgerring/sdlc-gitops-sample-stack/load-test-service
    newTag: "2113e1c327c0a334e2488d6210585614dc8e6be8"
