resources:
  - ../../base

# Patches for resources
patchesStrategicMerge:
  - aws-ingress-patch.yaml

configMapGenerator:
  - name: pass-api-config
    behavior: merge
    literals:
      - DD_ENV=dev
      - DD_VERSION=58ee967eafe577cb1860ecac34d62708b1251566

  - name: pass-summary-api-config
    behavior: merge
    literals:
      - DD_ENV=dev
      - DD_VERSION=58ee967eafe577cb1860ecac34d62708b1251566

  - name: pass-image-api-config
    behavior: merge
    literals:
      - DD_ENV=dev
      - DD_VERSION=58ee967eafe577cb1860ecac34d62708b1251566

  - name: load-test-service-config
    behavior: merge
    literals:
      - DD_ENV=dev
      - DD_VERSION=58ee967eafe577cb1860ecac34d62708b1251566

images:
  - name: ghcr.io/scottgerring/sdlc-gitops-sample-stack/pass-api
    newTag: "58ee967eafe577cb1860ecac34d62708b1251566"

  - name: ghcr.io/scottgerring/sdlc-gitops-sample-stack/pass-summary-api
    newTag: "58ee967eafe577cb1860ecac34d62708b1251566"

  - name: ghcr.io/scottgerring/sdlc-gitops-sample-stack/pass-image-api
    newTag: "58ee967eafe577cb1860ecac34d62708b1251566"

  - name: ghcr.io/scottgerring/sdlc-gitops-sample-stack/load-test-service
    newTag: "58ee967eafe577cb1860ecac34d62708b1251566"
