resources:
  - ../../base

configMapGenerator:
  - name: pass-api-config
    behavior: merge
    literals:
      - DD_ENV=dev
      - DD_VERSION=d0cb8e16abf50b5a5ddefabccef020995935f85d

  - name: pass-summary-api-config
    behavior: merge
    literals:
      - DD_ENV=dev
      - DD_VERSION=d0cb8e16abf50b5a5ddefabccef020995935f85d

  - name: pass-image-api-config
    behavior: merge
    literals:
      - DD_ENV=dev
      - DD_VERSION=d0cb8e16abf50b5a5ddefabccef020995935f85d

  - name: load-test-service-config
    behavior: merge
    literals:
      - DD_ENV=dev
      - DD_VERSION=d0cb8e16abf50b5a5ddefabccef020995935f85d

images:
  - name: ghcr.io/scottgerring/sdlc-gitops-sample-stack/pass-api
    newTag: "d0cb8e16abf50b5a5ddefabccef020995935f85d"

  - name: ghcr.io/scottgerring/sdlc-gitops-sample-stack/pass-summary-api
    newTag: "d0cb8e16abf50b5a5ddefabccef020995935f85d"

  - name: ghcr.io/scottgerring/sdlc-gitops-sample-stack/pass-image-api
    newTag: "d0cb8e16abf50b5a5ddefabccef020995935f85d"

  - name: ghcr.io/scottgerring/sdlc-gitops-sample-stack/load-test-service
    newTag: "d0cb8e16abf50b5a5ddefabccef020995935f85d"
