resources:
  - ../../base

configMapGenerator:
  - name: pass-api-config
    behavior: merge
    literals:
      - DD_ENV=dev
      - DD_VERSION=2bfb7d6bec360e32deb55a2db71f6196ad597497

  - name: pass-summary-api-config
    behavior: merge
    literals:
      - DD_ENV=dev
      - DD_VERSION=2bfb7d6bec360e32deb55a2db71f6196ad597497

  - name: pass-image-api-config
    behavior: merge
    literals:
      - DD_ENV=dev
      - DD_VERSION=2bfb7d6bec360e32deb55a2db71f6196ad597497

  - name: load-test-service-config
    behavior: merge
    literals:
      - DD_ENV=dev
      - DD_VERSION=2bfb7d6bec360e32deb55a2db71f6196ad597497

images:
  - name: ghcr.io/scottgerring/sdlc-gitops-sample-stack/pass-api
    newTag: "2bfb7d6bec360e32deb55a2db71f6196ad597497"

  - name: ghcr.io/scottgerring/sdlc-gitops-sample-stack/pass-summary-api
    newTag: "2bfb7d6bec360e32deb55a2db71f6196ad597497"

  - name: ghcr.io/scottgerring/sdlc-gitops-sample-stack/pass-image-api
    newTag: "2bfb7d6bec360e32deb55a2db71f6196ad597497"

  - name: ghcr.io/scottgerring/sdlc-gitops-sample-stack/load-test-service
    newTag: "2bfb7d6bec360e32deb55a2db71f6196ad597497"
